language: cpp

compiler:  
    - gcc
    - clang

before_install:
    - sudo apt-get install libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev libav-extra

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
